name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: 20
          bun-version: latest
      - run: bun install
      - run: bun run make

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: 20
          bun-version: latest
          registry-url: https://registry.npmjs.org/
      - run: bun run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.is_has_token}}
