name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/
      - run: bun install
      - run: bun run make
      - run: bun run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.is_has_token}}
